root: true
env:
  browser: true
  es2021: true
settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.ts'
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: 'never'
      ts: 'never'
